NNP STM Generic Remote Module: Core/app/module/acceltemp.c File Reference
acceltemp.c File Reference
#include "main.h"
#include "acceltemp.h"
#include "ObjDict.h"
#include "app.h"
Functions
void putAccelRegSingle (UNS8 regNo, UNS8 data)
UNS8 getAccelRegSingle (UNS8 regNo)
void putAccelReg (UNS8 regNo, UNS8 data, UNS8 length)
void getAccelReg (UNS8 regNo, UNS8 *data, UNS8 length)
void sleepAccelerometer (void)
puts Accelerometer to sleep
void changeModeIMU (UNS8 mode)
Changes functional mode of ISM330IS accelerometer.
void initAccelerometer (void)
Initializes Accelerometer.
void updateAccelerometer (void)
update Accelerometer
void sleepTemperature (void)
puts thermometer to sleep
void initTemperature (void)
initializes thermometer to default configuration
void updateTemperature (void)
Gets temperature reading via I2C.
void initDiagnostics (void)
void updateDiagnostics (void)
If disgnostics is enabled, update their entries in the OD.
Detailed Description
Date
Created on: Oct 14, 2024
Author
Jerry Ukwela (jeu6@.nosp@m.case.nosp@m..edu)
Definition in file acceltemp.c.
Function Documentation
changeModeIMU()
void changeModeIMU (UNS8 mode)
Changes functional mode of ISM330IS accelerometer.
Parameters
mode Mode to configure the IMU into
Definition at line 71 of file acceltemp.c.
Referenced by initAccelerometer(), and processNMTstateChange().
getAccelReg()
void getAccelReg (UNS8 regNo, UNS8 * data, UNS8 length)
Definition at line 50 of file acceltemp.c.
getAccelRegSingle()
UNS8 getAccelRegSingle (UNS8 regNo)
Definition at line 39 of file acceltemp.c.
initAccelerometer()
void initAccelerometer (void)
Initializes Accelerometer.
Definition at line 119 of file acceltemp.c.
Referenced by main().
initDiagnostics()
void initDiagnostics (void)
Definition at line 492 of file acceltemp.c.
initTemperature()
void initTemperature (void)
initializes thermometer to default configuration
Definition at line 441 of file acceltemp.c.
Referenced by main().
putAccelReg()
void putAccelReg (UNS8 regNo, UNS8 data, UNS8 length)
Definition at line 46 of file acceltemp.c.
putAccelRegSingle()
void putAccelRegSingle (UNS8 regNo, UNS8 data)
Definition at line 35 of file acceltemp.c.
sleepAccelerometer()
void sleepAccelerometer (void)
puts Accelerometer to sleep
Definition at line 59 of file acceltemp.c.
Referenced by processNMTstateChange().
sleepTemperature()
void sleepTemperature (void)
puts thermometer to sleep
Definition at line 430 of file acceltemp.c.
Referenced by processNMTstateChange().
updateAccelerometer()
void updateAccelerometer (void)
update Accelerometer
Definition at line 127 of file acceltemp.c.
Referenced by main().
updateDiagnostics()
void updateDiagnostics (void)
If disgnostics is enabled, update their entries in the OD.
Definition at line 501 of file acceltemp.c.
Referenced by main().
updateTemperature()
void updateTemperature (void)
Gets temperature reading via I2C.
Definition at line 450 of file acceltemp.c.