NNP STM Generic Remote Module: SYNC
SYNC
CANFestival
Functions
void SyncAlarm (CO_Data *d, UNS32 id)
<BRIEF> SyncAlarm
UNS32 OnCOB_ID_SyncUpdate (CO_Data *d, const indextable *unsused_indextable, UNS8 unsused_bSubindex)
This is called when Index 0x1005 is updated.
void startSYNC (CO_Data *d)
<BRIEF> startSYNC
void stopSYNC (CO_Data *d)
<BRIEF> stopSYNC
UNS8 sendSYNCMessage (CO_Data *d)
Transmit a SYNC message on CAN bus.
UNS8 sendSYNC (CO_Data *d)
Transmit a SYNC message and trigger sync TPDOs.
UNS8 processSYNC (CO_Data *d, Message *m)
This function is called when the node is receiving a SYNC message (cob-id = 0x80).
void _post_sync (CO_Data *d)
<BRIEF> _post_sync
void _post_TPDO (CO_Data *d)
<BRIEF> _post_TPDO
Detailed Description
Function Documentation
_post_sync()
void _post_sync (CO_Data * d)
<BRIEF> _post_sync
Parameters
*d Pointer on a CAN object data structure
Definition at line 165 of file sync.c.
_post_TPDO()
void _post_TPDO (CO_Data * d)
<BRIEF> _post_TPDO
Parameters
*d Pointer on a CAN object data structure
Definition at line 172 of file sync.c.
OnCOB_ID_SyncUpdate()
UNS32 OnCOB_ID_SyncUpdate (CO_Data * d, const indextable * unsused_indextable, UNS8 unsused_bSubindex)
This is called when Index 0x1005 is updated.
Parameters
*d Pointer on a CAN object data structure
unsused_indextable
unsused_bSubindex
Returns
Definition at line 47 of file sync.c.
Referenced by startSYNC().
processSYNC()
UNS8 processSYNC (CO_Data * d, Message * m)
This function is called when the node is receiving a SYNC message (cob-id = 0x80).
Modified from original CANFestival code to include reading a message from the SYNC object
Check if the node is in OERATIONAL mode. (other mode : return 0 but does nothing).
Get the SYNC cobId by reading the dictionary index 1005, check it does correspond to the received cobId
Trigger sync TPDO emission
Parameters
*d Pointer on a CAN object data structure
Returns
0 if OK, 0xFF if error
Definition at line 135 of file sync.c.
Referenced by canDispatch(), and sendSYNC().
sendSYNC()
UNS8 sendSYNC (CO_Data * d)
Transmit a SYNC message and trigger sync TPDOs.
Parameters
*d Pointer on a CAN object data structure
Returns
Definition at line 117 of file sync.c.
Referenced by SyncAlarm().
sendSYNCMessage()
UNS8 sendSYNCMessage (CO_Data * d)
Transmit a SYNC message on CAN bus.
Parameters
*d Pointer on a CAN object data structure
Returns
Definition at line 97 of file sync.c.
Referenced by sendSYNC().
startSYNC()
void startSYNC (CO_Data * d)
<BRIEF> startSYNC
Parameters
*d Pointer on a CAN object data structure
Definition at line 58 of file sync.c.
Referenced by OnCOB_ID_SyncUpdate(), processNMTstateChange(), and switchCommunicationState().
stopSYNC()
void stopSYNC (CO_Data * d)
<BRIEF> stopSYNC
Parameters
*d Pointer on a CAN object data structure
Definition at line 83 of file sync.c.
Referenced by processNMTstateChange(), startSYNC(), and switchCommunicationState().
SyncAlarm()
void SyncAlarm (CO_Data * d, UNS32 id)
<BRIEF> SyncAlarm
Parameters
*d Pointer on a CAN object data structure
id not used
Definition at line 33 of file sync.c.
Referenced by startSYNC().