NNP STM Generic Remote Module: Module Application
Module Application
Remote Module
Module Application Code.
Functions
void initAppTask (void)
Function called at the initialization of program.
void updateAppTask ()
Main application loop called from main.c.
void runAppTask (UNS32 param)
This task is run on the background thread to update parameters.
void processSYNCMessageForApp (Message *m)
Lets application process SYNC message if necessary.
void sleepApplication (void)
This function is called when the module recieves an NMT to enter low power mode.
void InitAppTaskValues (void)
Reinitializes application values when necessary.
Detailed Description
Module Application Code.
Function Documentation
initAppTask()
void initAppTask (void)
Function called at the initialization of program.
Note
Object Dictionary has already been restored by this point, module type, node, and serial number have also been set
Parameters
None
Return values
None
Definition at line 33 of file app.c.
Referenced by main().
InitAppTaskValues()
void InitAppTaskValues (void)
Reinitializes application values when necessary.
Note
Runs when node is stopped, entering waiting mode, entering stop stim mode
Parameters
None
Return values
None
Definition at line 136 of file app.c.
Referenced by EnterStopStimFunc(), EnterWaitingFunc(), and StopNodesFunc().
processSYNCMessageForApp()
void processSYNCMessageForApp (Message * m)
Lets application process SYNC message if necessary.
Parameters
*m 8 byte message sent with SYNC objects from PM
Note
Changes made to the Object Dictionary in this function will be present in the response to the network
Definition at line 112 of file app.c.
Referenced by processSYNC().
runAppTask()
void runAppTask (UNS32 param)
This task is run on the background thread to update parameters.
Parameters
param can be used for anything, and is passed down from updateAppTask()
Definition at line 59 of file app.c.
Referenced by updateAppTask().
sleepApplication()
void sleepApplication (void)
This function is called when the module recieves an NMT to enter low power mode.
Parameters
none
Definition at line 124 of file app.c.
Referenced by processNMTstateChange().
updateAppTask()
void updateAppTask (void)
Main application loop called from main.c.
Note
main.c sleep mode causes this function to be called once per SysTick (every 1ms)
Parameters
None
Return values
None
Definition at line 45 of file app.c.
Referenced by main().