NNP STM Generic Remote Module: PDO
PDO
CANFestival
Functions
UNS8 buildPDO (CO_Data *d, UNS8 numPdo, Message *pdo)
Copy all the data to transmit in process_var Prepare the PDO defined at index to be sent *pwCobId : returns the value of the cobid. (subindex 1)
UNS8 sendPDOrequest (CO_Data *d, UNS16 RPDOIndex)
Transmit a PDO request frame on the network to the slave.
UNS8 processPDO (CO_Data *d, Message *m)
Compute a PDO frame reception bus_id is hardware dependant.
void CopyBits (UNS8 NbBits, UNS8 *SrcByteIndex, UNS8 SrcBitIndex, UNS8 SrcBigEndian, UNS8 *DestByteIndex, UNS8 DestBitIndex, UNS8 DestBigEndian)
copy bit per bit in little endian
UNS8 sendPDOevent (CO_Data *d)
Used by the application to signal changes in process data that could be mapped to some TPDO. This do not necessarily imply PDO emission. Function iterates on all TPDO and look TPDO transmit type and content change before sending it.
void PDOEventTimerAlarm (CO_Data *d, UNS32 pdoNum)
Set timer for PDO event.
void PDOInhibitTimerAlarm (CO_Data *d, UNS32 pdoNum)
Inhibit timer for PDO event.
UNS8 _sendPDOevent (CO_Data *d, UNS8 isSyncEvent)
Function iterates on all TPDO and look TPDO transmit type and content change before sending it.
UNS32 TPDO_Communication_Parameter_Callback (CO_Data *d, const indextable *OD_entry, UNS8 bSubindex)
<BRIEF> TPDO_Communication_Parameter_Callback
void PDOInit (CO_Data *d)
Initialize PDO feature.
void PDOStop (CO_Data *d)
Stop PDO feature.
void sendPdo (CO_Data *d, UNS32 pdoNum, Message *pdo)
<BRIEF> sendPDO
Detailed Description
Function Documentation
_sendPDOevent()
UNS8 _sendPDOevent (CO_Data * d, UNS8 isSyncEvent)
Function iterates on all TPDO and look TPDO transmit type and content change before sending it.
Parameters
*d Pointer on a CAN object data structure
isSyncEvent
Definition at line 512 of file pdo.c.
Referenced by PDOEventTimerAlarm(), PDOInhibitTimerAlarm(), processSYNC(), and sendPDOevent().
buildPDO()
UNS8 buildPDO (CO_Data * d, UNS8 numPdo, Message * pdo)
Copy all the data to transmit in process_var Prepare the PDO defined at index to be sent *pwCobId : returns the value of the cobid. (subindex 1)
Parameters
*d Pointer on a CAN object data structure
numPdo The PDO number
*pdo Pointer on a CAN message structure
Returns
0 or 0xFF if error.
Definition at line 28 of file pdo.c.
Referenced by _sendPDOevent(), and processPDO().
CopyBits()
void CopyBits (UNS8 NbBits, UNS8 * SrcByteIndex, UNS8 SrcBitIndex, UNS8 SrcBigEndian, UNS8 * DestByteIndex, UNS8 DestBitIndex, UNS8 DestBigEndian)
copy bit per bit in little endian
Parameters
NbBits
SrcByteIndex
SrcBitIndex
SrcBigEndian
DestByteIndex
DestBitIndex
DestBigEndian
Definition at line 404 of file pdo.c.
Referenced by buildPDO(), and processPDO().
PDOEventTimerAlarm()
void PDOEventTimerAlarm (CO_Data * d, UNS32 pdoNum)
Set timer for PDO event.
Parameters
*d Pointer on a CAN object data structure
pdoNum The PDO number
Definition at line 481 of file pdo.c.
Referenced by _sendPDOevent(), processPDO(), and TPDO_Communication_Parameter_Callback().
PDOInhibitTimerAlarm()
void PDOInhibitTimerAlarm (CO_Data * d, UNS32 pdoNum)
Inhibit timer for PDO event.
Parameters
*d Pointer on a CAN object data structure
pdoNum The PDO number
Definition at line 496 of file pdo.c.
Referenced by _sendPDOevent().
PDOInit()
void PDOInit (CO_Data * d)
Initialize PDO feature.
Parameters
*d Pointer on a CAN object data structure
Definition at line 752 of file pdo.c.
Referenced by processNMTstateChange(), and switchCommunicationState().
PDOStop()
void PDOStop (CO_Data * d)
Stop PDO feature.
Parameters
*d Pointer on a CAN object data structure
Definition at line 790 of file pdo.c.
Referenced by processNMTstateChange(), and switchCommunicationState().
processPDO()
UNS8 processPDO (CO_Data * d, Message * m)
Compute a PDO frame reception bus_id is hardware dependant.
Parameters
*d Pointer on a CAN object data structure
*m Pointer on a CAN message structure
Returns
0xFF if error, else return 0
Definition at line 144 of file pdo.c.
Referenced by canDispatch().
sendPdo()
void sendPdo (CO_Data * d, UNS32 pdoNum, Message * pdo)
<BRIEF> sendPDO
Parameters
*d Pointer on a CAN object data structure
pdoNum
*pdo
Definition at line 820 of file pdo.c.
sendPDOevent()
UNS8 sendPDOevent (CO_Data * d)
Used by the application to signal changes in process data that could be mapped to some TPDO. This do not necessarily imply PDO emission. Function iterates on all TPDO and look TPDO transmit type and content change before sending it.
Parameters
*d Pointer on a CAN object data structure
Definition at line 468 of file pdo.c.
sendPDOrequest()
UNS8 sendPDOrequest (CO_Data * d, UNS16 RPDOIndex)
Transmit a PDO request frame on the network to the slave.
Parameters
*d Pointer on a CAN object data structure
RPDOIndex Index of the receive PDO
Returns
CanFestival file descriptor is returned upon success.
0xFF is returned if RPDO Index is not found.
0xFF if error, other in success.
Definition at line 102 of file pdo.c.
TPDO_Communication_Parameter_Callback()
UNS32 TPDO_Communication_Parameter_Callback (CO_Data * d, const indextable * OD_entry, UNS8 bSubindex)
<BRIEF> TPDO_Communication_Parameter_Callback
Parameters
d
OD_entry
bSubindex
Returns
always 0
Definition at line 715 of file pdo.c.
Referenced by PDOInit().