NNP STM Generic Remote Module: NMT Slave
NMT Slave
CANFestival
Functions
void processNMTstateChange (CO_Data *d, Message *m)
Manage the reception of a NMT message from the master.
UNS8 slaveSendBootUp (CO_Data *d)
Transmit the boot-Up frame when the slave is moving from initialization state to pre_operational state.
void StartWatchDog (CO_Data *d, UNS16 timebase)
Starts watchdog on slave.
void StopWatchDog (CO_Data *d)
Stops watchdog on slave.
void setNodeStateToStopped (void)
<BRIEF> setNodeStateToStopped
Detailed Description
Function Documentation
processNMTstateChange()
void processNMTstateChange (CO_Data * d, Message * m)
Manage the reception of a NMT message from the master.
Parameters
*d Pointer to the CAN data structure
*m Pointer to the message received
Returns
0 if OK
-1 if the slave is not allowed, by its state, to receive the message
Definition at line 34 of file nmtSlave.c.
Referenced by canDispatch().
setNodeStateToStopped()
void setNodeStateToStopped (void)
<BRIEF> setNodeStateToStopped
Definition at line 288 of file nmtSlave.c.
slaveSendBootUp()
UNS8 slaveSendBootUp (CO_Data * d)
Transmit the boot-Up frame when the slave is moving from initialization state to pre_operational state.
Parameters
*d Pointer on the CAN data structure
Returns
canSend(bus_id,&m)
Definition at line 234 of file nmtSlave.c.
Referenced by switchCommunicationState().
StartWatchDog()
void StartWatchDog (CO_Data * d, UNS16 timebase)
Starts watchdog on slave.
Parameters
*d Pointer on the CAN data structure
timebase
Definition at line 269 of file nmtSlave.c.
Referenced by EnterPatientManualFunc(), EnterXManualFunc(), EnterYManualFunc(), and processNMTstateChange().
StopWatchDog()
void StopWatchDog (CO_Data * d)
Stops watchdog on slave.
Parameters
*d Pointer on the CAN data structure
Definition at line 279 of file nmtSlave.c.
Referenced by EnterWaitingFunc().