NNP STM Generic Remote Module: Object Dictionary
Object Dictionary
CANFestival
Classes
struct struct_CO_Data
This structure contains all necessary informations to define a CANOpen node.
Functions
UNS32 RegisterSetODentryCallBack (CO_Data *d, UNS16 wIndex, UNS8 bSubindex, ODCallback_t Callback)
<BRIEF>
void _storeODSubIndex (CO_Data *d, UNS16 wIndex, UNS8 bSubindex)
<BRIEF>
Detailed Description
Function Documentation
_storeODSubIndex()
void _storeODSubIndex (CO_Data * d, UNS16 wIndex, UNS8 bSubindex)
<BRIEF>
Parameters
*d Pointer to a CAN object data structure
wIndex
bSubindex
Definition at line 376 of file objacces.c.
RegisterSetODentryCallBack()
UNS32 RegisterSetODentryCallBack (CO_Data * d, UNS16 wIndex, UNS8 bSubindex, ODCallback_t Callback)
<BRIEF>
Parameters
*d Pointer to a CAN object data structure
wIndex
bSubindex
Callback
Returns
errorCode
Definition at line 357 of file objacces.c.
Referenced by emergencyInit(), heartbeatInit(), startSYNC(), and stopSYNC().