NNP STM Generic Remote Module: Emergency
Emergency
CANFestival
Functions
UNS32 OnNumberOfErrorsUpdate (CO_Data *d, const indextable *unsused_indextable, UNS8 unsused_bSubindex)
This is called when Index 0x1003 is updated.
void emergencyInit (CO_Data *d)
Start EMCY consumer and producer.
void emergencyStop (CO_Data *d)
Stop EMCY producer and consumer.
UNS8 sendEMCY (CO_Data *d, UNS16 errCode, UNS8 errRegister)
<BRIEF> sendEMCY
UNS8 EMCY_setError (CO_Data *d, UNS16 errCode, UNS8 errRegMask, UNS16 addInfo)
Sets a new error with code errCode. Also sets corresponding bits in Error register (1001h)
void EMCY_errorRecovered (CO_Data *d, UNS16 errCode)
Indicates it has recovered from error errCode. Also clears corresponding bits in Error register (1001h)
void proceedEMCY (CO_Data *d, Message *m)
This function is responsible to process an EMCY canopen-message.
void _post_emcy (CO_Data *d, UNS8 nodeID, UNS16 errCode, UNS8 errReg)
<BRIEF> _post_emcy
Detailed Description
Function Documentation
_post_emcy()
void _post_emcy (CO_Data * d, UNS8 nodeID, UNS16 errCode, UNS8 errReg)
<BRIEF> _post_emcy
Parameters
*d Pointer on a CAN object data structure
nodeID
errCode The error code
errReg
Definition at line 231 of file emcy.c.
EMCY_errorRecovered()
void EMCY_errorRecovered (CO_Data * d, UNS16 errCode)
Indicates it has recovered from error errCode. Also clears corresponding bits in Error register (1001h)
Parameters
*d Pointer on a CAN object data structure
errCode The error code
Definition at line 162 of file emcy.c.
EMCY_setError()
UNS8 EMCY_setError (CO_Data * d, UNS16 errCode, UNS8 errRegMask, UNS16 addInfo)
Sets a new error with code errCode. Also sets corresponding bits in Error register (1001h)
Parameters
*d Pointer on a CAN object data structure
errCode The error code
errRegMask
addInfo
Returns
Definition at line 105 of file emcy.c.
emergencyInit()
void emergencyInit (CO_Data * d)
Start EMCY consumer and producer.
Parameters
*d Pointer on a CAN object data structure
Definition at line 50 of file emcy.c.
Referenced by switchCommunicationState().
emergencyStop()
void emergencyStop (CO_Data * d)
Stop EMCY producer and consumer.
Parameters
*d Pointer on a CAN object data structure
Definition at line 62 of file emcy.c.
Referenced by switchCommunicationState().
OnNumberOfErrorsUpdate()
UNS32 OnNumberOfErrorsUpdate (CO_Data * d, const indextable * unsused_indextable, UNS8 unsused_bSubindex)
This is called when Index 0x1003 is updated.
Parameters
*d Pointer on a CAN object data structure
unsused_indextable
unsused_bSubindex
Returns
Definition at line 32 of file emcy.c.
Referenced by emergencyInit().
proceedEMCY()
void proceedEMCY (CO_Data * d, Message * m)
This function is responsible to process an EMCY canopen-message.
Parameters
*d Pointer on a CAN object data structure
*m Pointer on the CAN-message which has to be analysed.
Definition at line 202 of file emcy.c.
Referenced by canDispatch().
sendEMCY()
UNS8 sendEMCY (CO_Data * d, UNS16 errCode, UNS8 errRegister)
<BRIEF> sendEMCY
Parameters
*d Pointer on a CAN object data structure
errCode The error code
errRegister
Returns
Definition at line 75 of file emcy.c.
Referenced by EMCY_errorRecovered(), and EMCY_setError().