NNP STM Generic Remote Module: FESCAN
FESCAN
Functions
void StartNodesFunc (CO_Data *d, Message *m)
Lets application process NMT_Start_Nodes (unused)
void StopNodesFunc (CO_Data *d, Message *m)
Lets application process NMT_Stop_Nodes.
void EnterWaitingFunc (CO_Data *d, Message *m)
Lets application process NMT_Enter_Waiting.
void EnterPatientOperationFunc (CO_Data *d, Message *m)
Lets application process NMT_Enter_Patient_Operation.
void EnterXManualFunc (CO_Data *d, Message *m)
Lets application process NMT_Enter_X_Manual.
void EnterYManualFunc (CO_Data *d, Message *m)
Lets application process NMT_Enter_Y_Manual.
void EnterStopStimFunc (CO_Data *d, Message *m)
Lets application process NMT_Enter_Stop_Stim.
void EnterPatientManualFunc (CO_Data *d, Message *m)
Lets application process NMT_Enter_Patient_Manual.
void EnterProduceXManualFunc (CO_Data *d, Message *m)
Lets application process NMT_Produce_X_Manual.
void EnterRecordXFunc (CO_Data *d, Message *m)
Lets application process NMT_Enter_Record_X.
UNS8 processBOOT (CO_Data *d, Message *m)
Initializes node ID and serial number data in the object dictionary.
UNS8 canSend (CAN_HandleTypeDef *hcan, Message *m)
The driver send a CAN message passed from the CANopen stack.
Detailed Description
Function Documentation
canSend()
UNS8 canSend (CAN_HandleTypeDef * hcan, Message * m)
The driver send a CAN message passed from the CANopen stack.
Parameters
hcan,CAN Handle
*m pointer to message to send
Returns
1 if hardware -> CAN frame
Definition at line 83 of file can_stm.c.
EnterPatientManualFunc()
void EnterPatientManualFunc (CO_Data * d, Message * m)
Lets application process NMT_Enter_Patient_Manual.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 250 of file app.c.
Referenced by processNMTstateChange().
EnterPatientOperationFunc()
void EnterPatientOperationFunc (CO_Data * d, Message * m)
Lets application process NMT_Enter_Patient_Operation.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 189 of file app.c.
Referenced by processNMTstateChange().
EnterProduceXManualFunc()
void EnterProduceXManualFunc (CO_Data * d, Message * m)
Lets application process NMT_Produce_X_Manual.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 266 of file app.c.
Referenced by processNMTstateChange().
EnterRecordXFunc()
void EnterRecordXFunc (CO_Data * d, Message * m)
Lets application process NMT_Enter_Record_X.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 281 of file app.c.
Referenced by processNMTstateChange().
EnterStopStimFunc()
void EnterStopStimFunc (CO_Data * d, Message * m)
Lets application process NMT_Enter_Stop_Stim.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 236 of file app.c.
Referenced by processNMTstateChange().
EnterWaitingFunc()
void EnterWaitingFunc (CO_Data * d, Message * m)
Lets application process NMT_Enter_Waiting.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 174 of file app.c.
Referenced by processNMTstateChange().
EnterXManualFunc()
void EnterXManualFunc (CO_Data * d, Message * m)
Lets application process NMT_Enter_X_Manual.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 204 of file app.c.
Referenced by processNMTstateChange().
EnterYManualFunc()
void EnterYManualFunc (CO_Data * d, Message * m)
Lets application process NMT_Enter_Y_Manual.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 220 of file app.c.
Referenced by processNMTstateChange().
processBOOT()
UNS8 processBOOT (CO_Data * d, Message * m)
Initializes node ID and serial number data in the object dictionary.
Definition at line 15 of file boot.c.
Referenced by canDispatch().
StartNodesFunc()
void StartNodesFunc (CO_Data * d, Message * m)
Lets application process NMT_Start_Nodes (unused)
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 147 of file app.c.
Referenced by processNMTstateChange().
StopNodesFunc()
void StopNodesFunc (CO_Data * d, Message * m)
Lets application process NMT_Stop_Nodes.
Parameters
*d Pointer to the CAN data structure
*m 3 byte message sent with NMT objects from PM
Definition at line 161 of file app.c.
Referenced by processNMTstateChange().