NNP STM Generic Remote Module: Heartbeat
Heartbeat
CANFestival
Functions
void processNODE_GUARD (CO_Data *d, Message *m)
This function is responsible to process a canopen-message which seams to be an NMT Error Control Messages. At them moment we assume that every NMT error control message is a heartbeat message. If a BootUp message is detected, it will return the nodeId of the Slave who booted up.
void ProducerHearbeatAlarm (CO_Data *d, UNS32 id)
the Consumer Timer Callback. Heartbeat has been modified to include module Serial Number
UNS32 OnHeartbeatProducerUpdate (CO_Data *d, const indextable *unsused_indextable, UNS8 unsused_bSubindex)
This is called when Index 0x1017 is updated.
void heartbeatInit (CO_Data *d)
Start heartbeat consumer and producer with respect to 0x1016 and 0x1017 object dictionary entries.
void heartbeatStop (CO_Data *d)
Stop heartbeat consumer and producer.
void _heartbeatError (CO_Data *d, UNS8 heartbeatID)
heartbeat Error
void _post_SlaveBootup (CO_Data *d, UNS8 SlaveID)
post slave bootup
Detailed Description
Function Documentation
_heartbeatError()
void _heartbeatError (CO_Data * d, UNS8 heartbeatID)
heartbeat Error
Parameters
*d Pointer on a CAN object data structure
heartbeatID
Definition at line 236 of file lifegrd.c.
_post_SlaveBootup()
void _post_SlaveBootup (CO_Data * d, UNS8 SlaveID)
post slave bootup
Parameters
*d Pointer on a CAN object data structure
SlaveID
Definition at line 244 of file lifegrd.c.
heartbeatInit()
void heartbeatInit (CO_Data * d)
Start heartbeat consumer and producer with respect to 0x1016 and 0x1017 object dictionary entries.
Parameters
*d Pointer on a CAN object data structure
Definition at line 189 of file lifegrd.c.
Referenced by OnHeartbeatProducerUpdate(), and switchCommunicationState().
heartbeatStop()
void heartbeatStop (CO_Data * d)
Stop heartbeat consumer and producer.
Parameters
*d Pointer on a CAN object data structure
Definition at line 219 of file lifegrd.c.
Referenced by OnHeartbeatProducerUpdate(), and switchCommunicationState().
OnHeartbeatProducerUpdate()
UNS32 OnHeartbeatProducerUpdate (CO_Data * d, const indextable * unsused_indextable, UNS8 unsused_bSubindex)
This is called when Index 0x1017 is updated.
Parameters
*d Pointer on a CAN object data structure
unsused_indextable
unsused_bSubindex
Returns
Definition at line 175 of file lifegrd.c.
Referenced by heartbeatInit().
processNODE_GUARD()
void processNODE_GUARD (CO_Data * d, Message * m)
This function is responsible to process a canopen-message which seams to be an NMT Error Control Messages. At them moment we assume that every NMT error control message is a heartbeat message. If a BootUp message is detected, it will return the nodeId of the Slave who booted up.
Parameters
*d Pointer on a CAN object data structure
*m Pointer on the CAN-message which has to be analysed.
Note
This feature is not used by the NNP
Notice that only the master can have sent this node guarding request
Receiving a NMT NodeGuarding (request of the state by the master) Only answer to the NMT NodeGuarding request, the master is not checked (not implemented)
Definition at line 68 of file lifegrd.c.
Referenced by canDispatch().
ProducerHearbeatAlarm()
void ProducerHearbeatAlarm (CO_Data * d, UNS32 id)
the Consumer Timer Callback. Heartbeat has been modified to include module Serial Number
Parameters
*d Pointer on a CAN object data structure
id
Definition at line 141 of file lifegrd.c.
Referenced by heartbeatInit().