NNP STM Generic Remote Module: Core/Src/st32/timer_stm.c File Reference
timer_stm.c File Reference
#include "timer.h"
#include "stm32l4xx.h"
#include "main.h"
Functions
void setTimer (TIMEVAL value)
Set the timer peripheral for the next interrupt.
void initTimer (void)
UNS8 isTimedOut (UNS32 *tRef, UNS32 tAlarm)
Checks if a timer has timed out.
void resetTimeOut (UNS32 *tRef)
Resets a timed out timer.
TIMEVAL getElapsedTime (void)
Return the elapsed time to tell the Stack how much time is spent since last call.
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Detailed Description
Created on: Oct 9, 2024 Author: jenej
Definition in file timer_stm.c.
Function Documentation
getElapsedTime()
TIMEVAL getElapsedTime (void)
Return the elapsed time to tell the Stack how much time is spent since last call.
Returns
value TIMEVAL (unsigned long) the elapsed time
Definition at line 63 of file timer_stm.c.
Referenced by SetAlarm(), and TimeDispatch().
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Definition at line 75 of file timer_stm.c.
initTimer()
void initTimer (void)
Definition at line 31 of file timer_stm.c.
isTimedOut()
UNS8 isTimedOut (UNS32 * tRef, UNS32 tAlarm)
Checks if a timer has timed out.
Definition at line 39 of file timer_stm.c.
Referenced by runAppTask(), updateAccelerometer(), updateDiagnostics(), and updateTemperature().
resetTimeOut()
void resetTimeOut (UNS32 * tRef)
Resets a timed out timer.
Definition at line 54 of file timer_stm.c.
Referenced by runAppTask(), updateAccelerometer(), updateDiagnostics(), and updateTemperature().
setTimer()
void setTimer (TIMEVAL value)
Set the timer peripheral for the next interrupt.
Definition at line 21 of file timer_stm.c.
Referenced by SetAlarm(), and TimeDispatch().